### PR TITLE
Backport allow_abbrev option from Python 3.5

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Comment by ThomasWaldmann** [comment]
Looks good. Do you need this in here for 2.6 compatibility?

**Comment by jd** [comment]
No, I don't care about Python 2.6 personally. I just need to for all Python < 3.5 though.

**Comment by ThomasWaldmann** [comment]
Well, a while ago I did a fix here to make a bug in python 3.2.early go away.

But then I noticed that when you have a python that HAS argparse in its stdlib (like 3.2) AND you install argparse from pypi additionally (to fix or add stuff, wanting to override stdlib), python will still import argparse from stdlib if you just do "import argparse", not the pypi package.

For my issue, I just added a non-broken argparse from 3.2.late to package.support.argparse and imported from there. crappy, but worked.

**Comment by jd** [comment]
Thanks for the heads-up @ThomasWaldmann. This really sucks indeed :(

**Comment by dominik-jastrzebski** [comment]
@jd @ThomasWaldmann any update? It would be nice to have this feature backported.

**Comment by ThomasWaldmann** [comment]
@dominik-jastrzebski did you read my comment above? do you need this for python 2.6?

**Comment by dominik-jastrzebski** [comment]
@ThomasWaldmann No, I don't need it for Python 2.6. Python 2.7 is just fine. I read your comment above, but I don't understand the connection between merging this PR and problems with installing the library while it's included in the stdlib.

**Comment by jd** [comment]
Installing the lib in Python 2.7 won't override the builtin module. You can pip install this, it will never be used in Python 2.7.

**Comment by jayvdb** [comment]
... and having an updated argparse in Python 2.7+ is the job of a larger project like https://github.com/PythonCharmers/python-future

**Pull request closed without merging**
